export const tabs = [
  {
    title: "Movies",
  },
  {
    title: "TV Shows",
  },
];

export const tvShowData = [
  {
    id: 1,
    href: "https://www.youtube.com/watch?v=ByAn8DF8Ykk",
    src: "/assets/images/1.jpg",
    alt: "number 1 image",
    src2: "/assets/images/Avatar-the-last-airbender.jpg",
    alt2: "Avatar the last airbender image",
    title: "Avatar the last airbender",
    desc: "Follow Aang, the young Avatar, as he learns to master the four elements (Water, Earth, Fire, and Air) to restore balance to a world threatened by the terrifying Fire Nation.",
    names: "Gordon Cormier, Kiawentiio, Ian Ousley"
  },
  {
    id: 2,
    href: "https://www.youtube.com/watch?v=WlopfWYGBh44",
    src: "/assets/images/2.jpg",
    alt: "number 2 image",
    src2: "/assets/images/One-Day.jpg",
    alt2: "One Day image",
    title: "One Day ",
    desc: `Emma and Dexter meet for the first time on the night of their graduation. Tomorrow they must go their separate ways.`,
    names: "Leo Woodall, Ampika Mod, Amber Grappy"
  },
  {
    id: 3,
    href: "https://www.youtube.com/watch?v=s2eBAFt3L_0",
    src: "/assets/images/3.jpg",
    alt: "number 3 image",
    src2: "/assets/images/Love-is-blind.jpg",
    alt2: "Love is Blind image",
    title: "Love is Blind",
    desc: `Singles who want to be loved for who they are, rather than what they look like, have signed up for a less-conventional approach to modern dating.`,
    names: "Nick Lachey, Vanessa Lachey ,Bartise Bowden"
  },
  {
    id: 4,
    href: "https://www.youtube.com/watch?v=wETXsRn1_gY",
    src: "/assets/images/4.jpg",
    alt: "number 4 image",
    src2: "/assets/images/can-tell-you-a-secret.jpg",
    alt2: "Can I Tell You A Secret?: Limited Series image",
    title: "Can I Tell You A Secret?: Limited Series",
    desc: `Three women's lives are changed forever when a prolific stalker infiltrates their social media accounts. And they're only a fraction of his many victims.`,
    names: "Savannah Gracey"
  },
  {
    id: 5,
    href: "https://www.youtube.com/watch?v=wcF0A-Gy-Ng",
    src: "/assets/images/5.jpg",
    alt: "number 5 image",
    src2: "/assets/images/try.jpg",
    alt2: "Griselda image",
    title: "Griselda",
    desc: `Fleeing from Medellín to Miami, Griselda Blanco creates one of the most ruthless cartels in history.`,
    names: "Sofía Vergara, Alberto Guerra, Juliana Aidén Martinez"
  },
  {
    id: 6,
    href: "https://www.youtube.com/watch?v=79rtcCnaeyo",
    src: "/assets/images/6.jpg",
    alt: "number 6 image",
    src2: "/assets/images/Warrior.jpg",
    alt2: "Warrior image",
    title: "Warrior",
    desc: `During the Tong Wars in the late 1800s, Ah Sahm, a martial arts prodigy from China, immigrates to San Francisco and becomes a hatchet man for the most powerful tong in Chinatown.`,
    names: "Andrew Koji, Olivia Cheng, Jason Tobin"
  },
  {
    id: 7,
    href: "https://www.youtube.com/watch?v=BO94mVGgWfQ",
    src: "/assets/images/7.jpg",
    alt: "number 7 image",
    src2: "/assets/images/Mike-Epps.jpg",
    alt2: "Mike Epps image ",
    title: "Mike Epps: Ready to Sell Out",
    desc: `Mike Epps reflects on his career success and personal struggles, touching on financial issues, relationships, and his signature comedic takes on life in the streets.`,
    names: "Mike Epps"
  },
  {
    id: 8,
    href: "https://www.youtube.com/watch?v=wtJPe1ksS6E",
    src: "/assets/images/8.jpg",
    alt: "number 8 image",
    src2: "/assets/images/formula.jpg",
    alt2: "Formula 1: Drive to Survive image",
    title: "Formula 1: Drive to Survive",
    desc: `Docuseries following the FIA Formula One World Championship across multiple seasons.`,
    names: "Will Buxton, Jack Nicholls, Daniel Ricciardo"
  },
  {
    id: 9,
    href: "https://www.youtube.com/watch?v=T4J7QjGNTs4",
    src: "/assets/images/9.jpg",
    alt: "number 9 image",
    src2: "/assets/images/Resident-alien.jpg",
    alt2: "Resident Alien image ",
    title: "Resident Alien",
    desc: `A crash-landed alien takes on the identity of a small-town Colorado doctor and slowly begins to wrestle with the moral dilemma of his secret mission on Earth.`,
    names: "Levi Fiehler, Judah Prehn, Elizabeth Bowen",
  },
  {
    id: 10,
    href: "https://www.youtube.com/watch?v=oIjbxpFvAzs",
    src: "/assets/images/10.jpg",
    alt: "number 10 image",
    src2: "/assets/images/The-turist.png",
    alt2: "The Tourist image",
    title: "The Tourist",
    desc: `When a man wakes up in the Australian outback with no memory, he must use the few clues he has to discover his identity before his past catches up with him.`,
    names: "Jamie Dornan, Danielle Macdonald, Greg Larsen",
  },
];

//Periexomeno tou Trending Component
export const movieData = [
  {
    id: 1,
    href: "https://www.youtube.com/watch?v=r71iiAEi-tA",
    src: "/assets/images/1.jpg",
    alt: "number 1 image",
    src2: "/assets/images/Heart-of-stone.jpg",
    alt2: "Heart of stone image ",
    title: "Heart of Stone",
    desc: "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable and dangerous weapon.",
    names: "Gal Gadot, Jamie Dornan, Alia Bhatt",
  },
  {
    id: 2,
    href: "https://www.youtube.com/watch?v=Kut3nPN04U4",
    src: "/assets/images/2.jpg",
    alt: "number 2 image",
    src2: "/assets/images/hidden-strike.jpg",
    alt2: "Hidden strike image ",
    title: "Hidden Strike",
    desc: `Two ex-special forces soldiers must escort a group of civilians along Baghdad's "Highway of Death" to the safety of the Green Zone.`,
    names: "John Cena, Jackie Chan",
  },
  {
    id: 3,
    href: "https://www.youtube.com/watch?v=zQHOWnoExSs",
    src: "/assets/images/3.jpg",
    alt: "number 3 image",
    src2: "/assets/images/Untold-johny-football.jpg",
    alt2: "Untold: Johnny Football image",
    title: "Untold Johnny football",
    desc: `This documentary traces the meteoric rise and precipitous fall of football star Johnny Manziel via interviews with friends, coaches and Manziel himself.`,
    names: "Eric Bolling, Blake Bortles ,Erik Burkhardt",
  },
  {
    id: 4,
    href: "https://www.youtube.com/watch?v=HeoLiTirRp4",
    src: "/assets/images/4.jpg",
    alt: "number 4 image",
    src2: "/assets/images/What-men-want.jpg",
    alt2: "What men want image",
    title: "What men want",
    desc: `A woman is boxed out by the male sports agents in her profession, but gains an unexpected edge over them when she develops the ability to hear men's thoughts.`,
    names: "Taraji P. Henson, Kristen Ledlow, Josh Brener",
  },
  {
    id: 5,
    href: "https://www.youtube.com/watch?v=3fzFvZToh8o",
    src: "/assets/images/5.jpg",
    alt: "number 5 image",
    src2: "/assets/images/ladybug.jpg",
    alt2: "ladybug image",
    title: "Miraculous: Ladybug & Cat Noir, The Movie",
    desc: `Ordinary teenager Marinette's life in Paris goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.`,
    names: "Antoine Tomé, Benjamin Bollen, Annouck Hautbois",
  },
  {
    id: 6,
    href: "https://www.youtube.com/watch?v=45Iuy6YmMBs",
    src: "/assets/images/6.jpg",
    alt: "number 6 image",
    src2: "/assets/images/Happiness-for-beginners.jpg",
    alt2: "Happiness for beginners image",
    title: "Happiness for begginers",
    desc: `Helen signs up for a wilderness survival course, a year after getting divorced. She discovers through this experience that sometimes, you have to get really lost in order to find yourself.`,
    names: "Ellie Kemper, Luke Grimes, Nico Santos",
  },
  {
    id: 7,
    href: "https://www.youtube.com/watch?v=TlbnGSMJQbQ",
    src: "/assets/images/7.jpg",
    alt: "number 7 image",
    src2: "/assets/images/Despicable-me-2.jpg",
    alt2: "Despicable me 2 image ",
    title: "Despicable me 2",
    desc: `When Gru, the world's most super-bad turned super-dad has been recruited by a team of officials to stop lethal muscle and a host of Gru's own, He has to fight back with new gadgetry, cars, and more minion madness.`,
    names: "Steve Carell, Kristen Wiig, Benjamin Bratt",
  },
  {
    id: 8,
    href: "https://www.youtube.com/watch?v=aqm16DRLgbo",
    src: "/assets/images/8.jpg",
    alt: "number 8 image",
    src2: "/assets/images/Shark-bait.jpg",
    alt2: "Shark bait image ",
    title: "Shark bait",
    desc: `A group of friends enjoying a weekend steal a couple of jetskis racing them out to sea, ending up in a horrific head-on collision. They struggle to find a way home with a badly injured friend while from the waters below predators lurk.`,
    names: "Holly Earl, Jack Trueman, Catherine Hannay",
  },
  {
    id: 9,
    href: "https://www.youtube.com/watch?v=tPWURGgKJ7o",
    src: "/assets/images/9.jpg",
    alt: "number 9 image",
    src2: "/assets/images/Fatale.jpg",
    alt2: "Fatale image ",
    title: "Fatale",
    desc: `After a one-night stand, a successful married man finds himself entangled in a cunning police detective's latest investigation.`,
    names: "Hilary Swank, Michael Ealy, Mike Colter",
  },
  {
    id: 10,
    href: "https://www.youtube.com/watch?v=J1Cr-y83-c0",
    src: "/assets/images/10.jpg",
    alt: "number 10 image",
    src2: "/assets/images/the-river-wild.jpg",
    alt2: "The river wild image ",
    title: "The river wild",
    desc: `Follows a pair of siblings who love but distrust each other as they embark on a white-water rafting trip with a small group. One of their friends from childhood turns out to be more dangerous than he appears.`,
    names: "Adam Brody, Courtney Chen, Eve Connolly",
  },
];

//Onomata tainiwn gia to search

export const movieTitles = ["Harry potter", "Star wars", "Lord of the rings"];
