//This is a list of profanity words that are used to filter out profanity from the reviews
export const profanityList = new Set([
    "fuck",
    "fucks",
    "fucking",
    "fucked",
    "fucker",
    "fuckers",
    "motherfuck",
    "motherfucker",
    "motherfuckers",
    "motherfucking",
    "motherfucked",
    "fuckin",
    "shit",
    "shits",
    "ass",
    "bitch",
    "bitching",
    "staboultzis",
    "σταμπουλτζης",
    "σταμπουλτζιος",
    "σταμπουλτζής",
  ])