//Components
import Nav from '@/app/components/Movie-components/Nav'

//layout
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./movieStyles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#EEE3CB] ${inter.className}`}>
        <Nav />
        {children}</body>
    </html>
  );
}
